Update PolynomialRingGF2m.cs
Add brackets around bit shift operations in For loop init and conditions to avoid compiler errors with VS2017 ("Error CS0118	'numColumns' is a variable but is used like a type").